// <auto-generated />

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("BBCode.Net")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("BBCode.Net")]
[assembly: AssemblyCopyright("Copyright © 2010 John Gietzen")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: Guid("a84a4962-aba5-4e56-b85e-fae25ced77ee")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
